# Generated by Django 4.1.7 on 2023-03-06 13:54

from django.db import migrations


def capitalize(apps, schema_editor):
    Product = apps.get_model('main', 'Product')
    for product in Product.objects.all():
        product.name = product.name.capitalize()
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productimage_thumbnail'),
    ]

    operations = [
        migrations.RunPython(
            capitalize,
            migrations.RunPython.noop,
        ),
    ]
