# Generated by Django 4.1.7 on 2023-03-08 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_producttag_managers_remove_producttag_products_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='producttag',
            managers=[
            ],
        ),
    ]
